title: Jeevan Modhugu
logo: /assets/img/1-modified.png
**EMAIL : jeevanreddymodhugu@gmail.com**
<p align="left">
<a href="https://linkedin.com/in/https://www.linkedin.com/in/jeevan-reddy-491819210/" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="https://www.linkedin.com/in/jeevan-reddy-491819210/" height="30" width="40" /></a>
</p>
theme: jekyll-theme-minimal
